---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml

  vars:
    beacon_service: 587c7432-e01a-11ec-8d93-6b4ba42e911c
    stereum_args:
      manage_service:
        save: true
        state: started
        configuration:
          service: PrysmBeaconService
          id: "{{ prysm_service }}"
          image: "stratisevm/prysm-beacon-chain:{{ stereum_static.defaults.versions.prysm }}"
          ports:
            - 0.0.0.0:12000:12000/udp
            - 0.0.0.0:13000:13000/tcp
          env: {}
          entrypoint: []
          command: |
            /app/cmd/beacon-chain/beacon-chain
            --accept-terms-of-use=true
            --datadir=/opt/app/beacon
            --p2p-host-ip=""
            --p2p-host-dns=""
            --auroria=true
            --block-batch-limit=512
            --rpc-host=0.0.0.0
            --grpc-gateway-host=0.0.0.0
            --p2p-max-peers=100
            --execution-endpoint=http://stereum-{{ geth_service }}:8551
            --monitoring-port=8080
            --monitoring-host=0.0.0.0
            --jwt-secret=/engine.jwt
          user: "2000"
          volumes:
            - "/opt/app/services/{{ prysm_service }}/prysm/beacon:/opt/app/beacon"
            - "/opt/app/services/{{ geth_service }}/engine.jwt:/engine.jwt"

  tasks:
    - set_fact:
        stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
    - name: "Include manage-service"
      include_role:
        name: "manage-service"
