---
- name: Prepare
  hosts: all
  roles:
    - role: '../'
  vars_files:
    - ../../../../defaults/stereum_defaults.yaml

  tasks:
    # - name: Install python for Ansible (Ubuntu)
    #   raw: apt update && apt install -y pip ansible
    #   become: true
    #   changed_when: false
    #   when: ansible_distribution == "Ubuntu"
    - name: Install apt repo deps (Ubuntu)
      apt:
        update_cache: yes
        name: software-properties-common
        state: present
      become: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Add source repository into sources list
      apt_repository:
        repo: "ppa:ansible/ansible"

    - name: Install ansible (Ubuntu)
      apt:
        update_cache: yes
        name:
          - pip
          - ansible
        state: present
      become: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y python38 tar ansible && yum remove -y python36
      become: true
      changed_when: false
      when: ansible_distribution == "CentOS"

    - include_role:
        name: "setup"

    - include_role:
        name: "configure-firewall"

    # now let's setup the repo same way as with
    # launcher/src/backend/NodeConnection.js#prepareStereumNode()
    # only with an old tag, then update to new tag
    - file:
        path: "/opt/stereum/ansible"
        state: directory
        owner: "root"
        group: "root"
        mode: 0644
      become: yes
    - ansible.builtin.command: "{{ item }}"
      args:
        chdir: "/opt/stereum/ansible"
      with_items:
      - "git init"
      - "git remote add -f stratis-node https://github.com/stratisproject/stratis-node.git" # FIXME
      - "git config core.sparseCheckout true"
      - "echo 'controls' >> .git/info/sparse-checkout"
      - "git checkout c531dc2e89ec30c289e886fb3ff2a763e92b21d5"

    # spin up some services to update
    - name: Write service configuration prysm beacon
      copy:
        dest: "/etc/stereum/services/9024aec6-12a8-456a-8096-ee7ef6f67167.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          service: PrysmBeaconService
          id: 9024aec6-12a8-456a-8096-ee7ef6f67167
          image: stratisevm/prysm-beacon-chain:latest
          ports:
            - 0.0.0.0:12000:12000/udp
            - 0.0.0.0:13000:13000/tcp
          env: {}
          entrypoint: []
          command:
            - /app/cmd/beacon-chain/beacon-chain
            - --accept-terms-of-use=true
            - --datadir=/opt/app/beacon
            - --p2p-host-ip=""
            - --p2p-host-dns=""
            - --auroria=true
            - --block-batch-limit=512
            - --rpc-host=0.0.0.0
            - --grpc-gateway-host=0.0.0.0
            - --p2p-max-peers=100
            - --monitoring-port=8080
            - --monitoring-host=0.0.0.0
          user: "2000"
          volumes:
            - "/opt/app/services/9024aec6-12a8-456a-8096-ee7ef6f67167/prysm/beacon:/opt/app/beacon"
          user: "2000"
          autoupdate: true
          network: auroria
      become: yes

    - name: Write service configuration prysm validator
      copy:
        dest: "/etc/stereum/services/f3a6cbe4-5e4b-4ba4-a0f2-2504b6750379.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          service: PrysmValidatorService
          id: f3a6cbe4-5e4b-4ba4-a0f2-2504b6750379
          configVersion: 1
          command:
            - /app/cmd/validator/validator
            - --accept-terms-of-use=true
            - --beacon-rpc-provider="stereum-9024aec6-12a8-456a-8096-ee7ef6f67167:4000"
            - --beacon-rpc-gateway-provider="stereum-9024aec6-12a8-456a-8096-ee7ef6f67167:3500"
            - --auroria
            - --datadir=/opt/app/data/db
            - --wallet-dir=/opt/app/data/wallets
            - --wallet-password-file=/opt/app/data/passwords/wallet-password
            - --monitoring-host=0.0.0.0
            - --grpc-gateway-port=7500
            - --grpc-gateway-host=0.0.0.0
            - --grpc-gateway-corsdomain="*"
            - --monitoring-host=0.0.0.0
            - --monitoring-port=8081
            - --suggested-fee-recipient=0x0000000000000000000000000000000000000000
            - --graffiti-file=/opt/app/graffitis/graffitis.yaml
            - --enable-builder=true
            - --enable-doppelganger=true
          entrypoint: []
          env: {}
          image: stratisevm/prysm-validator:latest
          ports:
            - 127.0.0.1:7500:7500/tcp
          volumes:
            - /opt/stereum/prysm-f3a6cbe4-5e4b-4ba4-a0f2-2504b6750379/data/db:/opt/app/data/db
            - /opt/stereum/prysm-f3a6cbe4-5e4b-4ba4-a0f2-2504b6750379/data/wallets:/opt/app/data/wallets
            - /opt/stereum/prysm-f3a6cbe4-5e4b-4ba4-a0f2-2504b6750379/data/passwords:/opt/app/data/passwords
            - /opt/stereum/prysm-f3a6cbe4-5e4b-4ba4-a0f2-2504b6750379/graffitis:/opt/app/graffitis
          user: "2000"
          autoupdate: true
          network: auroria
      become: yes

    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: false
            state: started
            configuration:
              id: 9024aec6-12a8-456a-8096-ee7ef6f67167

    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: false
            state: started
            configuration:
              id: f3a6cbe4-5e4b-4ba4-a0f2-2504b6750379

# EOF
