---
- name: Converge
  hosts: all
  vars:
    json_update_data: |
      {
          "auroria": {
              "PrysmBeaconService": [
                  "latest"
              ],
              "PrysmValidatorService": [
                  "latest"
              ],
          }
      }

  tasks:
    - name: json config
      set_fact:
        update_data_test:
          json: "{{ json_update_data | from_json }}"
    - name: "Include update-services"
      include_role:
        name: "update-services"

# EOF
