---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml
  vars:
    grafana_service: 62aa1873-7b62-410b-ae8e-2cd8615165b9

  tasks:
    # grafana service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: GrafanaService
              id: "{{ grafana_service }}"
              image: "grafana/grafana:{{ stereum_static.defaults.versions.grafana }}"
              ports:
                - 127.0.0.1:3000:3000/tcp
              command: "/run.sh"
              user: "2000"
              volumes:
                - "/opt/app/services/{{ grafana_service }}/grafana/provisioning:/etc/grafana/provisioning"
                - "/opt/app/services/{{ grafana_service }}/grafana/data:/var/lib/grafana"
                - "/opt/app/services/{{ grafana_service }}/grafana:/etc/grafana"
