---
- name: Remove "resume stereum-services-update" from crontab
  cron:
    name: "resume stereum-services-update"
    state: absent
  become: yes

- name: Set update data
  set_fact:
    update_data: |
      {
          stereum: [{
              name: 'HEAD',
              commit: 'main'
          }]
      }

- name: Checkout commit of latest version
  git:
    repo: https://github.com/stratisproject/stratis-node.git
    remote: stratis-node
    dest: "{{ stereum.settings.controls_install_path }}/ansible"
    version: "{{ (update_data.json['stereum'] | last)['commit'] }}"
    force: true
  when: stereum.override_gitcommit is undefined

- name: Checkout commit of specific version
  git:
    repo: https://github.com/stratisproject/stratis-node.git
    remote: stratis-node
    dest: "{{ stereum.settings.controls_install_path }}/ansible"
    version: "{{ stereum.override_gitcommit }}"
    force: true
  when: stereum.override_gitcommit is defined
# EOF
