---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml
  vars:
    json_update_data: |
      {
          "auroria": {
              "PrysmBeaconService": [
                  "latest"
              ],
              "PrysmValidatorService": [
                  "latest"
              ],
          }
          "stereum": [
              {
                  "name": "main",
                  "commit": "main"
              }
          ]
      }


  tasks:
    - set_fact:
        update_data_test:
          json: "{{ json_update_data | from_json }}"
    - set_fact:
        stereum:
          settings:
            controls_install_path: "/opt/stereum"
    - debug:
        msg: "{{ stereum }}"
    - name: "Include update-stereum"
      include_role:
        name: "update-stereum"