---
# - name: Download update metadata
#   uri:
#     url: https://stereum.net/downloads/updates.json
#     method: GET
#     return_content: yes
#     status_code: 200
#     body_format: json
#   register: update_data_download

- name: Read updates file
  slurp:
    src: "/opt/stereum/ansible/controls/roles/update-services/files/updates.json"
  register: update_data_raw
  become: yes

- name: Parse update file
  set_fact:
    update_data: "{{ update_data_raw['content'] | b64decode | from_json }}"

- name: List services
  find:
    paths: /etc/stereum/services
  register: services_data
  become: yes

- name: Define services in scope
  set_fact:
    services_to_update: "{{ services_data.files | map(attribute='path') | map('split', '/') | map('last') | map('split', '.') | map('first') }}"
  when: services_to_update is undefined

- name: Update services
  include_tasks: update-service.yml
  with_items: "{{ services_to_update }}"

# EOF
