---
# - name: Download update metadata
#   uri:
#     url: https://stereum.net/downloads/updates.json
#     method: GET
#     return_content: yes
#     status_code: 200
#     body_format: json
#   register: update_data_download

- name: Set update data
  set_fact:
    update_data_raw: '{ "stratis": { "PrysmBeaconService": ["latest"], "PrysmValidatorService": ["latest"], "GethService": ["latest"] }, "auroria": { "PrysmBeaconService": ["latest"], "PrysmValidatorService": ["latest"], "GethService": ["latest"] } }'

- name: Set update data
  set_fact:
    update_data: "{{ update_data_raw | from_json }}"

- name: List services
  find:
    paths: /etc/stereum/services
  register: services_data
  become: yes

- name: Define services in scope
  set_fact:
    services_to_update: "{{ services_data.files | map(attribute='path') | map('split', '/') | map('last') | map('split', '.') | map('first') }}"
  when: services_to_update is undefined

- name: Update services
  include_tasks: update-service.yml
  with_items: "{{ services_to_update }}"

# EOF
