---
- name: Prepare
  hosts: all
  roles:
    - role: '../'
  vars_files:
    - ../../../../defaults/stereum_defaults.yaml
  vars:
    beacon_service: 11bf77ec-e01a-11ec-9e44-fbfbee39c56b

  tasks:
    - name: Install python for Ansible (Ubuntu)
      apt:
        update_cache: yes
        name: pip
        state: present
      become: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y python38 tar && yum remove -y python36
      become: true
      changed_when: false
      when: ansible_distribution == "CentOS"

    - include_role:
        name: "setup"

    - name: Write service configuration
      copy:
        dest: "/etc/stereum/services/{{ beacon_service }}.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          command:
            - /app/cmd/beacon-chain/beacon-chain
            - --auroria
            - --accept-terms-of-use=true
            - --datadir=/opt/app/beacon
            - --p2p-host-dns=""
            - --block-batch-limit=512
            - --rpc-host=0.0.0.0
            - --grpc-gateway-host=0.0.0.0
            - --p2p-max-peers=100
            - --execution-endpoint=http://stereum-{{ geth_service }}:8551
            - --monitoring-host=0.0.0.0
            - --monitoring-port=8080
            - --p2p-tcp-port=13001
            - --p2p-udp-port=12001
            - --jwt-secret=/engine.jwt
          entrypoint: []
          env: {}
          service: PrysmBeaconService
          id: {{ beacon_service }}
          image: "stratisevm/prysm-beacon-chain:{{ stereum_static.defaults.versions.prysm }}"
          ports:
            - 0.0.0.0:13001:13001/tcp
            - 0.0.0.0:12001:12001/udp
            - 127.0.0.1:4000:4000/tcp
            - 127.0.0.1:3500:3500/tcp
          volumes:
            - "/opt/app/services/{{ beacon_service }}/prysm/beacon:/opt/app/beacon"
            - "/opt/app/services/{{ beacon_service }}/genesis:/opt/app/genesis"
          user: 2000
      become: yes

    # start the container
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: false
            state: started
            configuration:
              id: "{{ beacon_service }}"
